=begin
#Theme Parks Wiki V1 API

#api.themeparks.wiki

The version of the OpenAPI document: 1.0.0-alpha

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class LiveStatusType
    OPERATING = "OPERATING".freeze
    DOWN = "DOWN".freeze
    CLOSED = "CLOSED".freeze
    REFURBISHMENT = "REFURBISHMENT".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = LiveStatusType.constants.select { |c| LiveStatusType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #LiveStatusType" if constantValues.empty?
      value
    end
  end
end
