=begin
#Theme Parks Wiki V1 API

#api.themeparks.wiki

The version of the OpenAPI document: 1.0.0-alpha

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ReturnTimeState
    AVAILABLE = "AVAILABLE".freeze
    TEMP_FULL = "TEMP_FULL".freeze
    FINISHED = "FINISHED".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ReturnTimeState.constants.select { |c| ReturnTimeState::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ReturnTimeState" if constantValues.empty?
      value
    end
  end
end
