=begin
#Theme Parks Wiki V1 API

#api.themeparks.wiki

The version of the OpenAPI document: 1.0.0-alpha

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DestinationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DestinationsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DestinationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DestinationsApi' do
    it 'should create an instance of DestinationsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DestinationsApi)
    end
  end

  # unit tests for get_destinations
  # Get a list of supported destinations available on the live API
  # @param [Hash] opts the optional parameters
  # @return [DestinationsResponse]
  describe 'get_destinations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
