=begin
#Theme Parks Wiki V1 API

#api.themeparks.wiki

The version of the OpenAPI document: 1.0.0-alpha

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ReturnTimeState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ReturnTimeState do
  let(:instance) { OpenapiClient::ReturnTimeState.new }

  describe 'test an instance of ReturnTimeState' do
    it 'should create an instance of ReturnTimeState' do
      expect(instance).to be_instance_of(OpenapiClient::ReturnTimeState)
    end
  end
end
