=begin
#Theme Parks Wiki V1 API

#api.themeparks.wiki

The version of the OpenAPI document: 1.0.0-alpha

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/boarding_group_state'
require 'openapi_client/models/destination_entry'
require 'openapi_client/models/destination_park_entry'
require 'openapi_client/models/destinations_response'
require 'openapi_client/models/entity_child'
require 'openapi_client/models/entity_children_response'
require 'openapi_client/models/entity_data'
require 'openapi_client/models/entity_data_location'
require 'openapi_client/models/entity_live_data'
require 'openapi_client/models/entity_live_data_response'
require 'openapi_client/models/entity_schedule_response'
require 'openapi_client/models/entity_type'
require 'openapi_client/models/live_queue'
require 'openapi_client/models/live_queue_boardinggroup'
require 'openapi_client/models/live_queue_paidreturntime'
require 'openapi_client/models/live_queue_returntime'
require 'openapi_client/models/live_queue_standby'
require 'openapi_client/models/live_show_time'
require 'openapi_client/models/live_status_type'
require 'openapi_client/models/price_data'
require 'openapi_client/models/return_time_state'
require 'openapi_client/models/schedule_entry'
require 'openapi_client/models/tag_data'

# APIs
require 'openapi_client/api/destinations_api'
require 'openapi_client/api/entities_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
